[project]
name = "clearsky-solar-radiation"
version = "0.1.0"
description = "Demo project for modeling solar radiation with python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=8.31.0",
    "matplotlib>=3.10.0",
    "numpy>=2.2.1",
    "pandas>=2.2.3",
]
